### ISSUE TITLE
Quadrant

### ISSUE THREAD

**Issue by Olgaborys** [davecroman/TouchAndPlay#7]
great work for this! really fun my kids love it. May I ask whats the QUADRANT I II III IV for?

**Comment by davecroman** [comment]
Hi Olga! There are four quadrants and each quadrant refers to a 90-degree range of motion. Apologies it's not explained well in the game, but it is in the paper if you need to understand more about it. See this link: https://ieeexplore.ieee.org/abstract/document/6623680

There's a paywall for viewing the paper unfortunately so I'm also giving you a link to a personal copy which you can access for free: https://www.dropbox.com/s/ra0koj9j4p1rcaw/A%20Kinesthetic%20Game%20as%20a%20Motivational%20Aid%20and%20Monitor%20in%20Upper%20Extremities%20Burns%20Rehabilitation.pdf?dl=0

**Comment by Olgaborys** [comment]
Amazing! Thank you!
